#
# Module manifest for module 'triage'
#
# Generated by: mikes
#
# Generated on: 29-May-2026
#

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = ""

    # Version number of this module.
    ModuleVersion = "0.5"

    # Supported PSEditions
    CompatiblePSEditions = @("Desktop", "Core")

    # ID used to uniquely identify this module
    GUID = "9f06c931-3aee-4cab-a9a4-c5d6f28be783"

    # Author of this module
    Author = "Michael Sponheimer"

    # Company or vendor of this module
    CompanyName = "NOVA ICAC"

    # Copyright statement for this module
    Copyright = "Copyright (c) 2026 Michael Sponheimer. Licensed under the GNU General Public License v3.0 or later."

    # Description of the functionality provided by this module
    Description = "NOVA ICAC Windows Forensic Triage Suite"

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = "5.1"

    # Prerequisite variables left empty
    PowerShellHostName = ""
    PowerShellHostVersion = ""
    DotNetFrameworkVersion = ""
    CLRVersion = ""
    ProcessorArchitecture = ""

    # Keeping arrays clear of conflicting configurations
    RequiredModules = @()
    RequiredAssemblies = @()
    ScriptsToProcess = @()
    TypesToProcess = @()
    FormatsToProcess = @()

    # Modules to import as nested modules
    NestedModules = @(
        "functions.psm1",
        "triage.psm1",
        "GuiMain.psm1",
        "001_Device.psm1",
        "002_Users.psm1",
        "003_Network.psm1",
        "004_Processes.psm1",
        "005_System.psm1",
        "005A_System.psm1",
        "006_Prefetch.psm1",
        "007_EventLogs.psm1",
        "008_Firewall.psm1",
        "009_Encryption.psm1",
        "010_Internet.psm1",
        "Get_CaseArchive.psm1",
        "Get_ComputerDetails.psm1",
        "Get_ComputerRam.psm1",
        "Get_FileHashes.psm1",
        "Get_RunningProcesses.psm1",
        "Invoke_EncryptedDiskDetector.psm1"
    )

    # Functions to export from this module
    FunctionsToExport = @(
        "Get-InitialSetup",
        "Complete-CaseManifest",
        "Disable-PSReadLineHistory",
        "Dismount-TriageUserHives",
        "Export-PerUserRegistry",
        "Get-CaseArchive",
        "Get-ComputerDetails",
        "Get-ComputerRam",
        "Get-FileHashes",
        "Get-Gui",
        "Get-PerUserRegistrySubKey",
        "Get-PerUserRegistryValue",
        "Get-RunningProcesses",
        "Get-TriageBinary",
        "Get-TriageDeviceData",
        "Get-TriageEncryptionData",
        "Get-TriageEventLogData",
        "Get-TriageFirewallData",
        "Get-TriageInternetData",
        "Get-TriageNetworkData",
        "Get-TriagePrefetchData",
        "Get-TriageProcessData",
        "Get-TriageSystemData",
        "Get-TriageUserData",
        "Initialize-TriageSystemTools",
        "Invoke-EncryptedDiskDetector",
        "Invoke-DfirTriageScan",
        "Mount-TriageUserHives",
        "New-CaseManifest",
        "Read-LogHost",
        "Show-IsAdmin",
        "Show-Message",
        "Test-IfExists",
        "Write-LogMessage",
        "Write-OutputToCsv",
        "Write-OutputToFile",
        "Write-LaunchContext",
        "Test-TriageInteractive",
        "Read-YesNo",
        "Read-Required",
        "Show-TriageBanner",
        "Write-CaseInfo",
        "Invoke-RegistryCommand"
    )

    # Kept clean to maximize triage stability and performance
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
    DscResourcesToExport = @()
    ModuleList = @()

    # Empty during development to prevent spelling mismatches or missing comma
    # errors
    FileList = @()

    # Private data to pass to the module specified in RootModule/
    # ModuleToProcess. This may also contain a PSData hashtable with additional
    # module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in
            # online galleries.
            Tags = @("DFIR", "Forensics", "Triage", "Windows")

            # A URL to the license for this module.
            LicenseUri = "https://github.com/LongRangeBehaviorModificationSpecialist/WindowsTriageScript/blob/main/LICENSE"

            # A URL to the main website for this project.
            ProjectUri = "https://github.com/LongRangeBehaviorModificationSpecialist/WindowsTriageScript"

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''
}
